# Generated by Django 6.0.1 on 2026-01-20 04:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Estudiante', 'Estudiante'), ('Profesor', 'Profesor')], default='Estudiante', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('advisor', models.CharField(blank=True, max_length=255)),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('checked', 'Aprobado'), ('pending', 'Pendiente'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('score', models.IntegerField(default=0, help_text='Total score (0-20)')),
                ('diagramacion_score', models.IntegerField(default=0, help_text='Section score (0-5)')),
                ('contenido_score', models.IntegerField(default=0, help_text='Section score (0-15)')),
                ('stage1_passed', models.BooleanField(default=False, help_text='For Tesis only')),
                ('semester', models.CharField(max_length=20)),
                ('project_type', models.CharField(choices=[('proyecto', 'Proyecto (PTEG)'), ('tesis', 'Tesis (TEG)')], default='proyecto', max_length=10)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.project')),
            ],
        ),
    ]
