# Generated by Django 6.0.1 on 2026-01-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contenido_score',
            field=models.FloatField(default=0, help_text='Section score (0-15)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='diagramacion_score',
            field=models.FloatField(default=0, help_text='Section score (0-5)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='score',
            field=models.FloatField(default=0, help_text='Total score (0-20)'),
        ),
    ]
