# Generated by Django 6.0.1 on 2026-01-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachedfile',
            name='url',
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='file',
            field=models.FileField(default=1, upload_to='project_files/'),
            preserve_default=False,
        ),
    ]
