# Generated by Django 6.0.1 on 2026-01-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_attachedfile_url_attachedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
