# Generated by Django 6.0.1 on 2026-02-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_update_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Estudiante', 'Estudiante'), ('Jurado', 'Jurado'), ('Tutor', 'Tutor')], default='Estudiante', max_length=20),
        ),
    ]
