# Generated by Django 6.0.1 on 2026-02-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='semester',
            new_name='period',
        ),
    ]
