# Generated by Django 6.0.1 on 2026-02-14 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_project_semester_to_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
