# Generated by Django 6.0.1 on 2026-03-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_project_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contenido_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='diagramacion_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='score',
        ),
    ]
