# Generated by Django 6.0.1 on 2026-03-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_evaluation_updated_at_project_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
