# Generated by Django 6.0.1 on 2026-03-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
