# Generated by Django 6.0.1 on 2026-03-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_user_phone_alter_user_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='period',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
