# Generated by Django 6.0.1 on 2026-04-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_normalize_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=6),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1),
        ),
        migrations.AlterField(
            model_name='semester',
            name='period',
            field=models.CharField(help_text='Format: YYYY-01 or YYYY-02', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, help_text='Student/staff ID number', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
