# Generated by Django 6.0.1 on 2026-04-13 14:58

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_session_log'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
