# Generated by Django 6.0.1 on 2026-04-14 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_presentation_days', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_days', to='api.semester')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Hora de inicio HH:MM')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30, help_text='Duración estimada en minutos')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('jurado', models.ManyToManyField(blank=True, limit_choices_to={'role': 'Jurado'}, related_name='juried_presentations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='api.project')),
                ('tutor', models.ForeignKey(blank=True, limit_choices_to={'role': 'Tutor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_presentations', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='api.presentationday')),
            ],
            options={
                'ordering': ['day__date', 'start_time', 'order'],
                'constraints': [models.UniqueConstraint(fields=('day', 'project'), name='unique_project_per_day')],
            },
        ),
    ]
