# Generated by Django 6.0.1 on 2026-04-16 — hand-edited to use SeparateDatabaseAndState.
#
# The implicit M2M table api_presentation_jurado already exists in the database
# with columns (id, presentation_id, user_id).  We want to:
#   1. Tell Django's state that PresentationJuror is now the through-model
#      (full CreateModel in state_operations).
#   2. Only add the NEW columns to the existing table at the DB level
#      (RunSQL operations — no CREATE TABLE since the table already exists).
#   3. AlterField on Presentation.jurado in state only (Django forbids DB-level
#      M2M field changes; the physical table is already correct).
#
# Choosing SeparateDatabaseAndState over the "new-table + RunPython copy"
# approach because the existing table already has the right (presentation_id,
# user_id) foreign keys — the safer, simpler path with no data-copy risk.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_migrate_cedula_to_int'),
    ]

    operations = [
        # Operation 1: Register PresentationJuror in Django state; only add new
        # columns to the pre-existing api_presentation_jurado table in the DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PresentationJuror',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('individual_score', models.FloatField(blank=True, null=True)),
                        ('notified', models.BooleanField(default=False)),
                        ('notified_at', models.DateTimeField(blank=True, null=True)),
                        ('confirmed_attendance', models.BooleanField(default=False)),
                        ('attended', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('juror', models.ForeignKey(
                            db_column='user_id',
                            limit_choices_to={'role': 'Jurado'},
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='juror_entries',
                            to=settings.AUTH_USER_MODEL,
                        )),
                        ('presentation', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='juror_entries',
                            to='api.presentation',
                        )),
                    ],
                    options={
                        'db_table': 'api_presentation_jurado',
                        'ordering': ['presentation', 'id'],
                        'unique_together': {('presentation', 'juror')},
                    },
                ),
            ],
            database_operations=[
                # Add only the new columns; the table and its existing columns
                # (id, presentation_id, user_id) already exist.
                migrations.RunSQL(
                    sql="ALTER TABLE api_presentation_jurado ADD COLUMN individual_score REAL NULL;",
                    reverse_sql="SELECT 1;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE api_presentation_jurado ADD COLUMN notified INTEGER NOT NULL DEFAULT 0;",
                    reverse_sql="SELECT 1;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE api_presentation_jurado ADD COLUMN notified_at DATETIME NULL;",
                    reverse_sql="SELECT 1;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE api_presentation_jurado ADD COLUMN confirmed_attendance INTEGER NOT NULL DEFAULT 0;",
                    reverse_sql="SELECT 1;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE api_presentation_jurado ADD COLUMN attended INTEGER NOT NULL DEFAULT 0;",
                    reverse_sql="SELECT 1;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE api_presentation_jurado ADD COLUMN created_at DATETIME NULL;",
                    reverse_sql="SELECT 1;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE api_presentation_jurado ADD COLUMN updated_at DATETIME NULL;",
                    reverse_sql="SELECT 1;",
                ),
            ],
        ),
        # Operation 2: Update Django state so Presentation.jurado references
        # through=PresentationJuror.  No DB operation needed — the physical M2M
        # table is unchanged; Django just needs to know about the through-model.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='presentation',
                    name='jurado',
                    field=models.ManyToManyField(
                        blank=True,
                        limit_choices_to={'role': 'Jurado'},
                        related_name='juried_presentations',
                        through='api.PresentationJuror',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
