# Generated by Django 6.0.1 on 2026-04-23 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_presentation_juror_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Jurado asignado para evaluar este proyecto', limit_choices_to={'role': 'Jurado'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
