# Generated by Django 6.0.1 on 2026-04-24 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_backfill_project_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='failed_attempts',
        ),
    ]
