# Generated by Django 6.0.1 on 2026-04-24 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_project_failed_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('pending_review_1', 'Pendiente 1ra revisión'), ('pending_review_2', 'Pendiente 2da revisión'), ('pending_defense', 'Pendiente defensa oral'), ('approved', 'Aprobado'), ('failed_final', 'Reprobado (sin más intentos)')], max_length=20)),
                ('to_state', models.CharField(choices=[('pending_review_1', 'Pendiente 1ra revisión'), ('pending_review_2', 'Pendiente 2da revisión'), ('pending_defense', 'Pendiente defensa oral'), ('approved', 'Aprobado'), ('failed_final', 'Reprobado (sin más intentos)')], max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_state_overrides', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_overrides', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
