# Generated by Django 6.0.1 on 2026-04-24 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_stateoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_evaluation_received', models.BooleanField(default=True)),
                ('notify_state_change', models.BooleanField(default=True)),
                ('notify_assignment', models.BooleanField(default=True)),
                ('notify_comment_added', models.BooleanField(default=True)),
                ('notify_semester_changes', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
