# Generated by Django 6.0.1 on 2026-04-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_teg_state_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='stage1_passed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
